languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

[params.author]
  name = "Your Name"
  bio = "A short bio about you."
  # links = [
  #   { github = "https://github.com/username" },
  #   { twitter = "https://twitter.com/username" },
  # ]
